// UI strings. Add a language by adding a block with the same keys;
// anything missing falls back to English.
export const STRINGS = {
  en: {
    'nav.agenda': 'Agenda',
    'nav.calendar': 'Calendar',
    'nav.tasks': 'To Do',
    'nav.memos': 'Memos',
    'nav.contacts': 'Contacts',
    'view.day': 'Day',
    'view.week': 'Week',
    'view.month': 'Month',
    'view.year': 'Year',
    'view.list': 'List',

    'common.today': 'Today',
    'common.tomorrow': 'Tomorrow',
    'common.yesterday': 'Yesterday',
    'common.new': 'New',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.done': 'Done',
    'common.duplicate': 'Duplicate',
    'common.remove': 'Remove',
    'common.search': 'Search',
    'common.undo': 'Undo',
    'common.next': 'Next',
    'common.previous': 'Previous',

    'filter.all': 'All',
    'filter.label': 'Category',
    'cat.none': 'Unfiled',
    'cat.business': 'Business',
    'cat.personal': 'Personal',
    'cat.family': 'Family',
    'cat.holiday': 'Holiday',

    'week.short': 'Wk {n}',
    'week.long': 'Week {n}',
    'dur.min': '{n} min',
    'dur.h': '{n} h',
    'dur.hmin': '{h} h {m} min',
    'alarm.none': 'No alarm',
    'alarm.atTime': 'At start time',
    'alarm.minutes': '{n} minute before|{n} minutes before',
    'alarm.hours': '{n} hour before|{n} hours before',
    'alarm.days': '{n} day before|{n} days before',
    'alarm.minutesPlain': '{n} minute|{n} minutes',

    'agenda.appointments': 'Appointments',
    'agenda.contacts': 'People today',
    'agenda.upcoming': 'Next {n} days',
    'agenda.all': 'All',
    'agenda.countEvents': '{n} appointment|{n} appointments',
    'agenda.countTasks': '{n} task|{n} tasks',
    'agenda.now': 'Now',
    'agenda.next': 'Next',
    'agenda.noAppointments': 'No appointments. Enjoy the free time.',
    'agenda.noTasks': 'Nothing to do.',
    'agenda.noUpcoming': 'Nothing planned yet.',
    'agenda.emptyHint': 'Your agenda is empty. Add your first appointment to get going.',

    'day.nothing': 'Nothing planned for this day.',
    'day.tasksDue': '{n} task due|{n} tasks due',
    'month.openDay': 'Day view',
    'list.more': 'Show more (until {date})',
    'list.nothing': 'Nothing planned in the next {n} days.',
    'birthday.of': "{name}'s birthday",

    'event.new': 'New appointment',
    'event.edit': 'Edit appointment',
    'event.details': 'Appointment',
    'event.untitled': '(no title)',
    'event.allDay': 'All day',
    'event.titlePh': 'What is happening?',
    'event.saved': 'Appointment saved',
    'event.deleted': 'Appointment deleted',
    'event.newAt': 'New appointment at {time}',

    'editor.icon': 'Choose icon',
    'editor.noIcon': 'No icon',
    'editor.starts': 'Starts',
    'editor.ends': 'Ends',
    'editor.time': 'Time',
    'editor.repeat': 'Repeat',
    'editor.alarm': 'Alarm',
    'editor.category': 'Category',
    'editor.location': 'Location',
    'editor.locationPh': 'Where?',
    'editor.contacts': 'Contacts',
    'editor.addContact': 'Link contact',
    'editor.notes': 'Note',

    'repeat.none': 'Does not repeat',
    'repeat.daily': 'Daily',
    'repeat.weekly': 'Weekly',
    'repeat.monthlyDate': 'Monthly (same date)',
    'repeat.monthlyWeekday': 'Monthly (same weekday)',
    'repeat.yearly': 'Yearly',
    'repeat.interval': 'Every',
    'repeat.until': 'Until',
    'repeat.every.daily': 'Every day',
    'repeat.every.weekly': 'Every week',
    'repeat.every.monthly': 'Every month',
    'repeat.every.yearly': 'Every year',
    'repeat.everyN.daily': 'Every {n} days',
    'repeat.everyN.weekly': 'Every {n} weeks',
    'repeat.everyN.monthly': 'Every {n} months',
    'repeat.everyN.yearly': 'Every {n} years',
    'repeat.nth.1': 'first',
    'repeat.nth.2': 'second',
    'repeat.nth.3': 'third',
    'repeat.nth.4': 'fourth',
    'repeat.nth.5': 'last',

    'scope.editTitle': 'Change repeating appointment',
    'scope.deleteTitle': 'Delete repeating appointment',
    'scope.message': 'Apply this to which occurrences?',
    'scope.one': 'Only this one',
    'scope.future': 'This and future ones',
    'scope.all': 'All occurrences',

    'tasks.title': 'To Do',
    'tasks.quickAdd': 'Add a task and press Enter',
    'tasks.filter.all': 'Open',
    'tasks.filter.today': 'Due',
    'tasks.filter.upcoming': 'Upcoming',
    'tasks.filter.nodate': 'No date',
    'tasks.filter.done': 'Completed',
    'tasks.empty.all': 'All done. Nothing open.',
    'tasks.empty.today': 'Nothing due today.',
    'tasks.empty.upcoming': 'No upcoming tasks.',
    'tasks.empty.nodate': 'No tasks without a date.',
    'tasks.empty.done': 'No completed tasks yet.',
    'tasks.overdue': 'Overdue',
    'tasks.overdueN': '{n} overdue',
    'tasks.noDate': 'No date',
    'tasks.purge': 'Delete completed tasks',
    'tasks.purgeConfirm': 'Remove all completed tasks? You can undo this right after.',
    'tasks.purged': 'Completed tasks deleted',

    'task.new': 'New task',
    'task.edit': 'Edit task',
    'task.untitled': '(no title)',
    'task.titlePh': 'What needs doing?',
    'task.priority': 'Priority',
    'task.due': 'Due date',
    'task.nextWeek': 'Next week',
    'task.reminder': 'Reminder',
    'task.done': 'Completed',
    'task.toggle': 'Mark as done',
    'task.saved': 'Task saved',
    'task.added': 'Task added',
    'task.deleted': 'Task deleted',
    'task.completed': 'Task completed',
    'task.rolled': 'Done. Next one: {date}',
    'task.completions': 'Completed once so far.|Completed {n} times so far.',

    'followup.title': 'Follow-up',
    'followup.message': 'Create a follow-up with the same contacts and category.',
    'followup.prefix': 'Follow-up: {title}',
    'followup.taskTomorrow': 'Task for tomorrow',
    'followup.taskWeek': 'Task for next week',
    'followup.eventWeek': 'Appointment next week',
    'followup.eventPick': 'Appointment, pick a date',
    'followup.created': 'Follow-up created',

    'contacts.title': 'Contacts',
    'contacts.search': 'Search {n} contacts',
    'contacts.empty': 'No contacts yet.',
    'contacts.noMatch': 'No matching contacts.',
    'contacts.unnamed': '(no name)',
    'contact.new': 'New contact',
    'contact.edit': 'Edit contact',
    'contact.details': 'Contact',
    'contact.call': 'Call',
    'contact.sms': 'Text',
    'contact.email': 'Email',
    'contact.emailLabel': 'Email',
    'contact.map': 'Map',
    'contact.firstName': 'First name',
    'contact.lastName': 'Last name',
    'contact.company': 'Company',
    'contact.jobTitle': 'Job title',
    'contact.phones': 'Phone numbers',
    'contact.emails': 'Email addresses',
    'contact.addPhone': 'Add phone',
    'contact.addEmail': 'Add email',
    'contact.address': 'Address',
    'contact.birthday': 'Birthday',
    'contact.noYear': 'Year unknown',
    'contact.website': 'Website',
    'contact.history': 'History',
    'contact.upcoming': 'Upcoming',
    'contact.past': 'Past appointments',
    'contact.noHistory': 'Nothing linked to this contact yet.',
    'contact.saved': 'Contact saved',
    'contact.deleted': 'Contact deleted',
    'contact.meetWith': 'Meeting with {name}',
    'contact.callName': 'Call {name}',
    'phone.mobile': 'Mobile',
    'phone.work': 'Work',
    'phone.home': 'Home',
    'phone.pager': 'Pager',
    'phone.fax': 'Fax',
    'phone.other': 'Other',

    'memos.title': 'Memos',
    'memos.search': 'Search memos',
    'memos.empty': 'No memos yet.',
    'memos.noMatch': 'No matching memos.',
    'memo.new': 'New memo',
    'memo.untitled': '(empty memo)',
    'memo.placeholder': 'Start typing. The first line becomes the title.',
    'memo.deleted': 'Memo deleted',

    'reminder.title': 'Agendus Reminder',
    'reminder.followUp': 'Follow-up',
    'reminder.snooze': 'Snooze',
    'reminder.none': 'None',
    'reminder.ok': 'OK',
    'reminder.open': 'Open',
    'reminder.complete': 'Done',
    'reminder.snoozed': 'Snoozed for {n} minute|Snoozed for {n} minutes',

    'goto.title': 'Go to date',
    'goto.date': 'Date',

    'search.placeholder': 'Appointments, tasks, contacts, memos',
    'search.hint': 'Type to search everything at once.',
    'search.none': 'Nothing found for "{q}".',
    'search.appointments': 'Appointments',

    'welcome.title': 'Welcome to Agendus',
    'welcome.text': 'The classic Palm organizer, rebuilt for your phone. Everything you plan stays on this device.',
    'welcome.f1': 'Agenda: appointments, tasks and people for today on one screen',
    'welcome.f2': 'Day, week, month, year and list views',
    'welcome.f3': 'Link contacts to appointments and tasks',
    'welcome.f4': 'Alarms with snooze and follow-ups',
    'welcome.f5': 'Private: no account, works offline',
    'welcome.demo': 'Start with sample data',
    'welcome.empty': 'Start empty',

    'settings.title': 'Preferences',
    'settings.general': 'General',
    'settings.language': 'Language',
    'settings.auto': 'Automatic',
    'settings.theme': 'Look',
    'settings.themeLight': 'Light',
    'settings.themeDark': 'Dark',
    'settings.themeClassic': 'Classic Palm',
    'settings.weekStart': 'Week starts on',
    'settings.monday': 'Monday',
    'settings.sunday': 'Sunday',
    'settings.saturday': 'Saturday',
    'settings.timeFormat': 'Time format',
    'settings.calendar': 'Calendar',
    'settings.dayStart': 'Day starts at',
    'settings.dayEnd': 'Day ends at',
    'settings.duration': 'Default length',
    'settings.defaultAlarm': 'Default alarm',
    'settings.monthText': 'Show titles in month view',
    'settings.agendaDays': 'Agenda looks ahead',
    'settings.nDays': '{n} days',
    'settings.undatedInAgenda': 'Undated tasks in agenda',
    'settings.doneInAgenda': 'Completed tasks in agenda',
    'settings.notifications': 'Alarms',
    'settings.notifyStatus': 'System notifications',
    'settings.notifyHint': 'Alarms ring while Agendus is open or in the background. Install it on your home screen for the best result.',
    'settings.notifyEnable': 'Turn on',
    'settings.notifyOn': 'Notifications are on',
    'settings.notifyDenied': 'Notifications are blocked. Allow them in your browser settings.',
    'settings.notifyUnsupported': 'Not supported in this browser',
    'settings.categories': 'Categories',
    'settings.addCategory': 'Add category',
    'settings.newCategory': 'New category',
    'settings.color': 'Colour',
    'settings.categoryName': 'Category name',
    'settings.deleteCategory': 'Delete category',
    'settings.deleteCategoryMsg': 'Items in "{name}" become Unfiled.',
    'settings.categoryDeleted': 'Category deleted',
    'settings.data': 'Your data',
    'settings.localNote': 'Everything is stored on this device only. Make a backup now and then.',
    'settings.memoryOnly': 'This browser blocks storage, so changes are lost when you close the page. Make a backup before leaving.',
    'settings.backup': 'Back up (.json)',
    'settings.restore': 'Restore backup',
    'settings.restoreConfirm': 'This replaces all current data with the backup. You can undo right after.',
    'settings.restoreReplace': 'Replace my data',
    'settings.restored': 'Backup restored',
    'settings.exportIcs': 'Export calendar (.ics)',
    'settings.importIcs': 'Import calendar (.ics)',
    'settings.exportVcf': 'Export contacts (.vcf)',
    'settings.importVcf': 'Import contacts (.vcf)',
    'settings.importedIcs': 'Imported {e} appointments and {t} tasks',
    'settings.importedVcf': 'Imported {n} contact|Imported {n} contacts',
    'settings.badFile': 'That file could not be read.',
    'settings.demo': 'Add sample data',
    'settings.demoLoaded': 'Sample data added',
    'settings.erase': 'Erase everything',
    'settings.eraseConfirm': 'Delete all appointments, tasks, contacts and memos?',
    'settings.erased': 'Everything erased',
    'settings.about': 'Agendus Web. A tribute to Agendus by Iambic for Palm OS.',
    'settings.stats': '{e} appointments, {t} tasks, {c} contacts, {m} memos',
  },

  nl: {
    'nav.agenda': 'Agenda',
    'nav.calendar': 'Kalender',
    'nav.tasks': 'Taken',
    'nav.memos': 'Memo’s',
    'nav.contacts': 'Contacten',
    'view.day': 'Dag',
    'view.week': 'Week',
    'view.month': 'Maand',
    'view.year': 'Jaar',
    'view.list': 'Lijst',

    'common.today': 'Vandaag',
    'common.tomorrow': 'Morgen',
    'common.yesterday': 'Gisteren',
    'common.new': 'Nieuw',
    'common.save': 'Opslaan',
    'common.cancel': 'Annuleren',
    'common.close': 'Sluiten',
    'common.delete': 'Verwijderen',
    'common.edit': 'Bewerken',
    'common.done': 'Klaar',
    'common.duplicate': 'Kopiëren',
    'common.remove': 'Weghalen',
    'common.search': 'Zoeken',
    'common.undo': 'Ongedaan maken',
    'common.next': 'Volgende',
    'common.previous': 'Vorige',

    'filter.all': 'Alles',
    'filter.label': 'Categorie',
    'cat.none': 'Ongeordend',
    'cat.business': 'Werk',
    'cat.personal': 'Persoonlijk',
    'cat.family': 'Familie',
    'cat.holiday': 'Vakantie',

    'week.short': 'Wk {n}',
    'week.long': 'Week {n}',
    'dur.min': '{n} min',
    'dur.h': '{n} u',
    'dur.hmin': '{h} u {m} min',
    'alarm.none': 'Geen alarm',
    'alarm.atTime': 'Bij aanvang',
    'alarm.minutes': '{n} minuut vooraf|{n} minuten vooraf',
    'alarm.hours': '{n} uur vooraf',
    'alarm.days': '{n} dag vooraf|{n} dagen vooraf',
    'alarm.minutesPlain': '{n} minuut|{n} minuten',

    'agenda.appointments': 'Afspraken',
    'agenda.contacts': 'Mensen vandaag',
    'agenda.upcoming': 'Komende {n} dagen',
    'agenda.all': 'Alles',
    'agenda.countEvents': '{n} afspraak|{n} afspraken',
    'agenda.countTasks': '{n} taak|{n} taken',
    'agenda.now': 'Nu',
    'agenda.next': 'Hierna',
    'agenda.noAppointments': 'Geen afspraken. Geniet van de vrije tijd.',
    'agenda.noTasks': 'Niets te doen.',
    'agenda.noUpcoming': 'Nog niets gepland.',
    'agenda.emptyHint': 'Je agenda is leeg. Zet je eerste afspraak erin om te beginnen.',

    'day.nothing': 'Niets gepland op deze dag.',
    'day.tasksDue': '{n} taak voor deze dag|{n} taken voor deze dag',
    'month.openDay': 'Dagweergave',
    'list.more': 'Meer tonen (tot {date})',
    'list.nothing': 'Niets gepland in de komende {n} dagen.',
    'birthday.of': 'Verjaardag {name}',

    'event.new': 'Nieuwe afspraak',
    'event.edit': 'Afspraak bewerken',
    'event.details': 'Afspraak',
    'event.untitled': '(geen titel)',
    'event.allDay': 'Hele dag',
    'event.titlePh': 'Wat gaat er gebeuren?',
    'event.saved': 'Afspraak opgeslagen',
    'event.deleted': 'Afspraak verwijderd',
    'event.newAt': 'Nieuwe afspraak om {time}',

    'editor.icon': 'Kies icoon',
    'editor.noIcon': 'Geen icoon',
    'editor.starts': 'Begint',
    'editor.ends': 'Eindigt',
    'editor.time': 'Tijd',
    'editor.repeat': 'Herhalen',
    'editor.alarm': 'Alarm',
    'editor.category': 'Categorie',
    'editor.location': 'Locatie',
    'editor.locationPh': 'Waar?',
    'editor.contacts': 'Contacten',
    'editor.addContact': 'Contact koppelen',
    'editor.notes': 'Notitie',

    'repeat.none': 'Herhaalt niet',
    'repeat.daily': 'Dagelijks',
    'repeat.weekly': 'Wekelijks',
    'repeat.monthlyDate': 'Maandelijks (zelfde datum)',
    'repeat.monthlyWeekday': 'Maandelijks (zelfde weekdag)',
    'repeat.yearly': 'Jaarlijks',
    'repeat.interval': 'Elke',
    'repeat.until': 'Tot en met',
    'repeat.every.daily': 'Elke dag',
    'repeat.every.weekly': 'Elke week',
    'repeat.every.monthly': 'Elke maand',
    'repeat.every.yearly': 'Elk jaar',
    'repeat.everyN.daily': 'Elke {n} dagen',
    'repeat.everyN.weekly': 'Elke {n} weken',
    'repeat.everyN.monthly': 'Elke {n} maanden',
    'repeat.everyN.yearly': 'Elke {n} jaar',
    'repeat.nth.1': 'eerste',
    'repeat.nth.2': 'tweede',
    'repeat.nth.3': 'derde',
    'repeat.nth.4': 'vierde',
    'repeat.nth.5': 'laatste',

    'scope.editTitle': 'Herhalende afspraak wijzigen',
    'scope.deleteTitle': 'Herhalende afspraak verwijderen',
    'scope.message': 'Voor welke keren geldt dit?',
    'scope.one': 'Alleen deze',
    'scope.future': 'Deze en volgende',
    'scope.all': 'Allemaal',

    'tasks.title': 'Taken',
    'tasks.quickAdd': 'Typ een taak en druk op Enter',
    'tasks.filter.all': 'Open',
    'tasks.filter.today': 'Nu doen',
    'tasks.filter.upcoming': 'Binnenkort',
    'tasks.filter.nodate': 'Zonder datum',
    'tasks.filter.done': 'Afgerond',
    'tasks.empty.all': 'Alles af. Niets open.',
    'tasks.empty.today': 'Niets voor vandaag.',
    'tasks.empty.upcoming': 'Geen taken gepland.',
    'tasks.empty.nodate': 'Geen taken zonder datum.',
    'tasks.empty.done': 'Nog niets afgerond.',
    'tasks.overdue': 'Te laat',
    'tasks.overdueN': '{n} te laat',
    'tasks.noDate': 'Geen datum',
    'tasks.purge': 'Afgeronde taken verwijderen',
    'tasks.purgeConfirm': 'Alle afgeronde taken verwijderen? Je kunt dit direct daarna ongedaan maken.',
    'tasks.purged': 'Afgeronde taken verwijderd',

    'task.new': 'Nieuwe taak',
    'task.edit': 'Taak bewerken',
    'task.untitled': '(geen titel)',
    'task.titlePh': 'Wat moet er gebeuren?',
    'task.priority': 'Prioriteit',
    'task.due': 'Deadline',
    'task.nextWeek': 'Volgende week',
    'task.reminder': 'Herinnering',
    'task.done': 'Afgerond',
    'task.toggle': 'Afvinken',
    'task.saved': 'Taak opgeslagen',
    'task.added': 'Taak toegevoegd',
    'task.deleted': 'Taak verwijderd',
    'task.completed': 'Taak afgerond',
    'task.rolled': 'Gedaan. Volgende keer: {date}',
    'task.completions': 'Tot nu toe {n} keer afgerond.',

    'followup.title': 'Opvolgen',
    'followup.message': 'Maak een vervolg met dezelfde contacten en categorie.',
    'followup.prefix': 'Opvolgen: {title}',
    'followup.taskTomorrow': 'Taak voor morgen',
    'followup.taskWeek': 'Taak voor volgende week',
    'followup.eventWeek': 'Afspraak volgende week',
    'followup.eventPick': 'Afspraak, zelf datum kiezen',
    'followup.created': 'Vervolg aangemaakt',

    'contacts.title': 'Contacten',
    'contacts.search': 'Zoek in {n} contacten',
    'contacts.empty': 'Nog geen contacten.',
    'contacts.noMatch': 'Geen contacten gevonden.',
    'contacts.unnamed': '(geen naam)',
    'contact.new': 'Nieuw contact',
    'contact.edit': 'Contact bewerken',
    'contact.details': 'Contact',
    'contact.call': 'Bellen',
    'contact.sms': 'Sms',
    'contact.email': 'Mailen',
    'contact.emailLabel': 'E-mail',
    'contact.map': 'Kaart',
    'contact.firstName': 'Voornaam',
    'contact.lastName': 'Achternaam',
    'contact.company': 'Bedrijf',
    'contact.jobTitle': 'Functie',
    'contact.phones': 'Telefoonnummers',
    'contact.emails': 'E-mailadressen',
    'contact.addPhone': 'Nummer toevoegen',
    'contact.addEmail': 'E-mail toevoegen',
    'contact.address': 'Adres',
    'contact.birthday': 'Verjaardag',
    'contact.noYear': 'Jaar onbekend',
    'contact.website': 'Website',
    'contact.history': 'Geschiedenis',
    'contact.upcoming': 'Gepland',
    'contact.past': 'Eerdere afspraken',
    'contact.noHistory': 'Nog niets gekoppeld aan dit contact.',
    'contact.saved': 'Contact opgeslagen',
    'contact.deleted': 'Contact verwijderd',
    'contact.meetWith': 'Afspraak met {name}',
    'contact.callName': '{name} bellen',
    'phone.mobile': 'Mobiel',
    'phone.work': 'Werk',
    'phone.home': 'Thuis',
    'phone.pager': 'Pieper',
    'phone.fax': 'Fax',
    'phone.other': 'Overig',

    'memos.title': 'Memo’s',
    'memos.search': 'Zoek in memo’s',
    'memos.empty': 'Nog geen memo’s.',
    'memos.noMatch': 'Geen memo’s gevonden.',
    'memo.new': 'Nieuwe memo',
    'memo.untitled': '(lege memo)',
    'memo.placeholder': 'Begin met typen. De eerste regel wordt de titel.',
    'memo.deleted': 'Memo verwijderd',

    'reminder.title': 'Agendus herinnering',
    'reminder.followUp': 'Opvolgen',
    'reminder.snooze': 'Sluimeren',
    'reminder.none': 'Geen',
    'reminder.ok': 'OK',
    'reminder.open': 'Openen',
    'reminder.complete': 'Afvinken',
    'reminder.snoozed': 'Sluimert {n} minuten',

    'goto.title': 'Naar datum',
    'goto.date': 'Datum',

    'search.placeholder': 'Afspraken, taken, contacten, memo’s',
    'search.hint': 'Typ om overal tegelijk te zoeken.',
    'search.none': 'Niets gevonden voor "{q}".',
    'search.appointments': 'Afspraken',

    'welcome.title': 'Welkom bij Agendus',
    'welcome.text': 'De klassieke Palm-organizer, opnieuw gebouwd voor je telefoon. Alles wat je plant blijft op dit apparaat.',
    'welcome.f1': 'Agenda: afspraken, taken en mensen van vandaag op één scherm',
    'welcome.f2': 'Dag, week, maand, jaar en lijst',
    'welcome.f3': 'Koppel contacten aan afspraken en taken',
    'welcome.f4': 'Alarmen met sluimeren en opvolgen',
    'welcome.f5': 'Privé: geen account, werkt offline',
    'welcome.demo': 'Begin met voorbeelddata',
    'welcome.empty': 'Begin leeg',

    'settings.title': 'Voorkeuren',
    'settings.general': 'Algemeen',
    'settings.language': 'Taal',
    'settings.auto': 'Automatisch',
    'settings.theme': 'Uiterlijk',
    'settings.themeLight': 'Licht',
    'settings.themeDark': 'Donker',
    'settings.themeClassic': 'Klassieke Palm',
    'settings.weekStart': 'Week begint op',
    'settings.monday': 'Maandag',
    'settings.sunday': 'Zondag',
    'settings.saturday': 'Zaterdag',
    'settings.timeFormat': 'Tijdnotatie',
    'settings.calendar': 'Kalender',
    'settings.dayStart': 'Dag begint om',
    'settings.dayEnd': 'Dag eindigt om',
    'settings.duration': 'Standaardduur',
    'settings.defaultAlarm': 'Standaardalarm',
    'settings.monthText': 'Titels tonen in maandweergave',
    'settings.agendaDays': 'Agenda kijkt vooruit',
    'settings.nDays': '{n} dagen',
    'settings.undatedInAgenda': 'Taken zonder datum in agenda',
    'settings.doneInAgenda': 'Afgeronde taken in agenda',
    'settings.notifications': 'Alarmen',
    'settings.notifyStatus': 'Systeemmeldingen',
    'settings.notifyHint': 'Alarmen gaan af zolang Agendus open is of op de achtergrond draait. Zet de app op je beginscherm voor het beste resultaat.',
    'settings.notifyEnable': 'Aanzetten',
    'settings.notifyOn': 'Meldingen staan aan',
    'settings.notifyDenied': 'Meldingen zijn geblokkeerd. Sta ze toe in je browserinstellingen.',
    'settings.notifyUnsupported': 'Niet beschikbaar in deze browser',
    'settings.categories': 'Categorieën',
    'settings.addCategory': 'Categorie toevoegen',
    'settings.newCategory': 'Nieuwe categorie',
    'settings.color': 'Kleur',
    'settings.categoryName': 'Naam categorie',
    'settings.deleteCategory': 'Categorie verwijderen',
    'settings.deleteCategoryMsg': 'Items in "{name}" worden Ongeordend.',
    'settings.categoryDeleted': 'Categorie verwijderd',
    'settings.data': 'Je gegevens',
    'settings.localNote': 'Alles staat alleen op dit apparaat. Maak af en toe een back-up.',
    'settings.memoryOnly': 'Deze browser blokkeert opslag, dus wijzigingen zijn weg als je de pagina sluit. Maak een back-up voordat je weggaat.',
    'settings.backup': 'Back-up maken (.json)',
    'settings.restore': 'Back-up terugzetten',
    'settings.restoreConfirm': 'Dit vervangt al je huidige gegevens door de back-up. Je kunt dit direct daarna ongedaan maken.',
    'settings.restoreReplace': 'Vervang mijn gegevens',
    'settings.restored': 'Back-up teruggezet',
    'settings.exportIcs': 'Kalender exporteren (.ics)',
    'settings.importIcs': 'Kalender importeren (.ics)',
    'settings.exportVcf': 'Contacten exporteren (.vcf)',
    'settings.importVcf': 'Contacten importeren (.vcf)',
    'settings.importedIcs': '{e} afspraken en {t} taken geïmporteerd',
    'settings.importedVcf': '{n} contacten geïmporteerd',
    'settings.badFile': 'Dit bestand kon niet worden gelezen.',
    'settings.demo': 'Voorbeelddata toevoegen',
    'settings.demoLoaded': 'Voorbeelddata toegevoegd',
    'settings.erase': 'Alles wissen',
    'settings.eraseConfirm': 'Alle afspraken, taken, contacten en memo’s verwijderen?',
    'settings.erased': 'Alles gewist',
    'settings.about': 'Agendus Web. Een eerbetoon aan Agendus van Iambic voor Palm OS.',
    'settings.stats': '{e} afspraken, {t} taken, {c} contacten, {m} memo’s',

    'demo.dentist': 'Tandarts',
    'demo.standup': 'Teamoverleg',
    'demo.gym': 'Sportschool',
    'demo.lunch': 'Lunch met Cathy',
    'demo.conference': 'Marketingcongres',
    'demo.payday': 'Salaris',
    'demo.flight': 'Vlucht naar Lissabon',
    'demo.review': 'Projectreview',
    'demo.boarding': 'Instapkaart printen',
    'demo.dinner': 'Tafel reserveren voor het diner',
    'demo.callWilliam': 'William bellen over de offerte',
    'demo.birthdayReminder': 'Verjaardagsherinnering sturen',
    'demo.plants': 'Planten water geven',
    'demo.passport': 'Paspoort verlengen',
    'demo.memo1': 'Paklijst Lissabon\n- Paspoort\n- Oplader\n- Zonnebril\n- Reisgids',
    'demo.memo2': 'Ideeën voor de congrestalk\nBegin met het Palm-verhaal en laat dan de nieuwe roadmap zien.',
  },
};
