// UI strings. Add a language by adding a block with the same keys;
// anything missing falls back to English.
export const STRINGS = {
  en: {
    'nav.agenda': 'Agenda',
    'nav.calendar': 'Calendar',
    'nav.tasks': 'To Do',
    'nav.memos': 'Memos',
    'nav.contacts': 'Contacts',
    'view.day': 'Day',
    'view.week': 'Week',
    'view.month': 'Month',
    'view.year': 'Year',
    'view.list': 'List',

    'common.today': 'Today',
    'common.tomorrow': 'Tomorrow',
    'common.yesterday': 'Yesterday',
    'common.new': 'New',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.done': 'Done',
    'common.duplicate': 'Duplicate',
    'common.remove': 'Remove',
    'common.search': 'Search',
    'common.undo': 'Undo',
    'common.on': 'ON',
    'common.off': 'OFF',
    'common.next': 'Next',
    'common.previous': 'Previous',

    'filter.all': 'All',
    'filter.label': 'Category',
    'cat.none': 'Unfiled',
    'cat.business': 'Business',
    'cat.personal': 'Personal',
    'cat.family': 'Family',
    'cat.holiday': 'Holiday',

    'week.short': 'Wk {n}',
    'week.long': 'Week {n}',
    'dur.min': '{n} min',
    'dur.h': '{n} h',
    'dur.hmin': '{h} h {m} min',
    'alarm.none': 'No alarm',
    'alarm.atTime': 'At start time',
    'alarm.minutes': '{n} minute before|{n} minutes before',
    'alarm.hours': '{n} hour before|{n} hours before',
    'alarm.days': '{n} day before|{n} days before',
    'alarm.minutesPlain': '{n} minute|{n} minutes',

    'agenda.appointments': 'Appointments',
    'agenda.contacts': 'People today',
    'agenda.upcoming': 'Next {n} days',
    'agenda.all': 'All',
    'agenda.countEvents': '{n} appointment|{n} appointments',
    'agenda.countTasks': '{n} task|{n} tasks',
    'agenda.now': 'Now',
    'agenda.next': 'Next',
    'agenda.noAppointments': 'No appointments. Enjoy the free time.',
    'agenda.noTasks': 'Nothing to do.',
    'agenda.noUpcoming': 'Nothing planned yet.',
    'agenda.emptyHint': 'Your agenda is empty. Add your first appointment to get going.',

    'day.nothing': 'Nothing planned for this day.',
    'day.tasksDue': '{n} task due|{n} tasks due',
    'month.openDay': 'Day view',
    'list.more': 'Show more (until {date})',
    'list.nothing': 'Nothing planned in the next {n} days.',
    'birthday.of': "{name}'s birthday",

    'event.new': 'New appointment',
    'event.edit': 'Edit appointment',
    'event.details': 'Appointment',
    'event.untitled': '(no title)',
    'event.allDay': 'All day',
    'event.titlePh': 'What is happening?',
    'event.saved': 'Appointment saved',
    'event.deleted': 'Appointment deleted',
    'event.newAt': 'New appointment at {time}',

    'editor.icon': 'Choose icon',
    'editor.noIcon': 'No icon',
    'editor.starts': 'Starts',
    'editor.ends': 'Ends',
    'editor.time': 'Time',
    'editor.repeat': 'Repeat',
    'editor.alarm': 'Alarm',
    'editor.category': 'Category',
    'editor.location': 'Location',
    'editor.locationPh': 'Where?',
    'editor.contacts': 'Contacts',
    'editor.addContact': 'Link contact',
    'editor.notes': 'Note',

    'repeat.none': 'Does not repeat',
    'repeat.daily': 'Daily',
    'repeat.weekly': 'Weekly',
    'repeat.monthlyDate': 'Monthly (same date)',
    'repeat.monthlyWeekday': 'Monthly (same weekday)',
    'repeat.yearly': 'Yearly',
    'repeat.interval': 'Every',
    'repeat.until': 'Until',
    'repeat.every.daily': 'Every day',
    'repeat.every.weekly': 'Every week',
    'repeat.every.monthly': 'Every month',
    'repeat.every.yearly': 'Every year',
    'repeat.everyN.daily': 'Every {n} days',
    'repeat.everyN.weekly': 'Every {n} weeks',
    'repeat.everyN.monthly': 'Every {n} months',
    'repeat.everyN.yearly': 'Every {n} years',
    'repeat.nth.1': 'first',
    'repeat.nth.2': 'second',
    'repeat.nth.3': 'third',
    'repeat.nth.4': 'fourth',
    'repeat.nth.5': 'last',

    'scope.editTitle': 'Change repeating appointment',
    'scope.deleteTitle': 'Delete repeating appointment',
    'scope.message': 'Apply this to which occurrences?',
    'scope.one': 'Only this one',
    'scope.future': 'This and future ones',
    'scope.all': 'All occurrences',

    'tasks.title': 'To Do',
    'tasks.quickAdd': 'Add a task and press Enter',
    'tasks.filter.all': 'Open',
    'tasks.filter.today': 'Due',
    'tasks.filter.upcoming': 'Upcoming',
    'tasks.filter.nodate': 'No date',
    'tasks.filter.done': 'Completed',
    'tasks.empty.all': 'All done. Nothing open.',
    'tasks.empty.today': 'Nothing due today.',
    'tasks.empty.upcoming': 'No upcoming tasks.',
    'tasks.empty.nodate': 'No tasks without a date.',
    'tasks.empty.done': 'No completed tasks yet.',
    'tasks.overdue': 'Overdue',
    'tasks.overdueN': '{n} overdue',
    'tasks.noDate': 'No date',
    'tasks.purge': 'Delete completed tasks',
    'tasks.purgeConfirm': 'Remove all completed tasks? You can undo this right after.',
    'tasks.purged': 'Completed tasks deleted',

    'task.new': 'New task',
    'task.edit': 'Edit task',
    'task.untitled': '(no title)',
    'task.titlePh': 'What needs doing?',
    'task.priority': 'Priority',
    'task.due': 'Due date',
    'task.nextWeek': 'Next week',
    'task.reminder': 'Reminder',
    'task.done': 'Completed',
    'task.toggle': 'Mark as done',
    'task.saved': 'Task saved',
    'task.added': 'Task added',
    'task.deleted': 'Task deleted',
    'task.completed': 'Task completed',
    'task.rolled': 'Done. Next one: {date}',
    'task.completions': 'Completed once so far.|Completed {n} times so far.',

    'followup.title': 'Follow-up',
    'followup.message': 'Create a follow-up with the same contacts and category.',
    'followup.prefix': 'Follow-up: {title}',
    'followup.taskTomorrow': 'Task for tomorrow',
    'followup.taskWeek': 'Task for next week',
    'followup.eventWeek': 'Appointment next week',
    'followup.eventPick': 'Appointment, pick a date',
    'followup.created': 'Follow-up created',

    'contacts.title': 'Contacts',
    'contacts.search': 'Search {n} contacts',
    'contacts.empty': 'No contacts yet.',
    'contacts.noMatch': 'No matching contacts.',
    'contacts.unnamed': '(no name)',
    'contact.new': 'New contact',
    'contact.edit': 'Edit contact',
    'contact.details': 'Contact',
    'contact.call': 'Call',
    'contact.sms': 'Text',
    'contact.email': 'Email',
    'contact.emailLabel': 'Email',
    'contact.map': 'Map',
    'contact.firstName': 'First name',
    'contact.lastName': 'Last name',
    'contact.company': 'Company',
    'contact.jobTitle': 'Job title',
    'contact.phones': 'Phone numbers',
    'contact.emails': 'Email addresses',
    'contact.addPhone': 'Add phone',
    'contact.addEmail': 'Add email',
    'contact.address': 'Address',
    'contact.birthday': 'Birthday',
    'contact.noYear': 'Year unknown',
    'contact.website': 'Website',
    'contact.history': 'History',
    'contact.upcoming': 'Upcoming',
    'contact.past': 'Past appointments',
    'contact.noHistory': 'Nothing linked to this contact yet.',
    'contact.saved': 'Contact saved',
    'contact.deleted': 'Contact deleted',
    'contact.meetWith': 'Meeting with {name}',
    'contact.callName': 'Call {name}',
    'phone.mobile': 'Mobile',
    'phone.work': 'Work',
    'phone.home': 'Home',
    'phone.pager': 'Pager',
    'phone.fax': 'Fax',
    'phone.other': 'Other',

    'memos.title': 'Memos',
    'memos.search': 'Search memos',
    'memos.empty': 'No memos yet.',
    'memos.noMatch': 'No matching memos.',
    'memo.new': 'New memo',
    'memo.untitled': '(empty memo)',
    'memo.placeholder': 'Start typing. The first line becomes the title.',
    'memo.deleted': 'Memo deleted',

    'reminder.title': 'Reminder',
    'reminder.followUp': 'Follow-up',
    'reminder.snooze': 'Snooze',
    'reminder.none': 'None',
    'reminder.ok': 'OK',
    'reminder.open': 'Open',
    'reminder.complete': 'Done',
    'reminder.snoozed': 'Snoozed for {n} minute|Snoozed for {n} minutes',

    'goto.title': 'Go to date',
    'goto.date': 'Date',

    'search.placeholder': 'Appointments, tasks, contacts, memos',
    'search.hint': 'Type to search everything at once.',
    'search.none': 'Nothing found for "{q}".',
    'search.appointments': 'Appointments',

    'welcome.title': 'Welcome to PalmOS Agenda',
    'welcome.text': 'The classic Palm organizer, rebuilt for your phone. Everything you plan stays on this device.',
    'welcome.f1': 'Agenda: appointments, tasks and people for today on one screen',
    'welcome.f2': 'Day, week, month, year and list views',
    'welcome.f3': 'Link contacts to appointments and tasks',
    'welcome.f4': 'Alarms with snooze and follow-ups',
    'welcome.f5': 'Private: no account, works offline',
    'welcome.demo': 'Start with sample data',
    'welcome.empty': 'Start empty',

    'ai.talkTo': "Talk to {name}",
    'ai.talk': "Talk",
    'ai.speak': "Speak",
    'ai.send': "Send",
    'ai.placeholder': "Ask or tell me something",
    'ai.placeholderMic': "Type, or tap Talk and speak",
    'ai.standby': "{name} standing by. Tap to talk.",
    'ai.greet': "{name} online. How can I help?",
    'ai.greetNews': "Online. {n} thing needs your attention.|Online. {n} things need your attention.",
    'ai.dismiss': "Dismiss",
    'ai.open': "Open",
    'ai.route': "Route",
    'ai.textLate': "Text {name}",
    'ai.lateMessage': "Hi! I'm on my way, see you soon. ({title})",
    'ai.moveToday': "Move to today",
    'ai.moveTomorrow': "Move to tomorrow",
    'ai.moved': "Tasks moved",
    'ai.giftTask': "Remind me: gift",
    'ai.giftTitle': "Get a present for {name}",
    'ai.at': " at {place}",
    'ai.insight.next': "{title} in {n} minute{where}, at {time}.|{title} in {n} minutes{where}, at {time}.",
    'ai.insight.clash': "{a} and {b} overlap {day} at {time}.",
    'ai.insight.busy': "No breathing room from {from} to {to}. Shall I find you a break?",
    'ai.insight.overdue': "\"{title}\" is overdue.|{n} tasks are overdue, starting with \"{title}\".",
    'ai.insight.bdayToday': "It's {name}'s birthday today{age}.",
    'ai.insight.bdayTomorrow': "{name}'s birthday is tomorrow{age}.",
    'ai.insight.early': "Early start tomorrow: {title} at {time}.",
    'ai.brief.morning': "Good morning{name}.",
    'ai.brief.afternoon': "Good afternoon{name}.",
    'ai.brief.evening': "Good evening{name}.",
    'ai.brief.free': "Nothing left on the calendar today.",
    'ai.brief.count': "You have {n} appointment left today:|You have {n} appointments left today:",
    'ai.brief.atTime': "at {time}",
    'ai.brief.tasks': "And {n} task on your list.|And {n} tasks on your list.",
    'ai.chip.next': "What's next?",
    'ai.chip.nextPrompt': "What's next on my agenda?",
    'ai.chip.brief': "Brief me",
    'ai.chip.briefPrompt': "Give me a short briefing of my day.",
    'ai.chip.tomorrow': "Plan tomorrow",
    'ai.chip.tomorrowPrompt': "What does tomorrow look like, and is there anything I should prepare?",
    'ai.chip.task': "Add a task",
    'ai.chip.taskPrefix': "Remind me to ",
    'ai.status.listening': "Listening...",
    'ai.status.thinking': "Thinking...",
    'ai.status.working': "Working on your agenda...",
    'ai.status.speaking': "Speaking",
    'ai.status.ready': "Ready",
    'ai.status.offline': "Offline mode",
    'ai.done': "Done.",
    'ai.undone': "Undone",
    'ai.refused': "I'm afraid I can't help with that one.",
    'ai.sendText': "Send text to {name}",
    'ai.sendEmail': "Email {name}",
    'ai.connect': "Connect Claude",
    'ai.localNote': "Offline mode: I understand simple commands. Connect Claude in Preferences to talk freely.",
    'ai.local.next': "Next up: {title}, {when}.",
    'ai.local.nothingNext': "Nothing planned for the next two weeks.",
    'ai.local.dayFree': "That day is still free.",
    'ai.local.dayCount': "{n} appointment:|{n} appointments:",
    'ai.local.taskAdded': "Added to your list: {title}.",
    'ai.local.needKey': "In offline mode I only know a few commands, like \"what's next\", \"today\", \"tomorrow\" or \"remind me to...\". Connect Claude in Preferences and I'll understand everything.",
    'ai.error.auth': "My connection to Claude was refused. Please check the API key in Preferences.",
    'ai.error.rate': "Claude is busy right now. Try again in a moment.",
    'ai.error.network': "I can't reach Claude. Are you online?",
    'ai.error.bad': "Claude didn't accept that request. Try saying it differently.",
    'ai.error.api': "Something went wrong on Claude's side. Try again in a moment.",
    'ai.error.other': "Something went wrong. Try again.",
    'ai.error.mic': "I'm not allowed to use the microphone. Allow it in your browser settings, or type instead.",
    'ai.reminderSay': "{name}a reminder:",
    'ai.voiceTest': "This is {name}. All systems are working perfectly.",
    'ai.keyInvalid': "That doesn't look like a Claude API key (it starts with sk-ant-).",
    'ai.keySaved': "Claude connected",
    'ai.keyRemoved': "API key removed",
    'ai.settings.title': "Assistant",
    'ai.settings.name': "Assistant's name",
    'ai.settings.userName': "Your name",
    'ai.settings.userNamePh': "Optional",
    'ai.settings.key': "Claude API key",
    'ai.settings.keyHint': "Needed to talk freely. Without it, simple commands still work.",
    'ai.settings.connected': "Connected",
    'ai.settings.forget': "Remove",
    'ai.settings.keyPrivacy': "Stored only on this device and sent only to Anthropic. It isn't included in backups. Get a key and set a monthly spending limit at",
    'ai.settings.model': "Model",
    'ai.settings.modelHint': "Opus is the smartest; Haiku is the fastest and cheapest.",
    'ai.settings.proactive': "Speak up proactively",
    'ai.settings.proactiveHint': "Tips about clashes, overdue tasks, birthdays and what's next.",
    'ai.settings.speak': "Speak replies aloud",
    'ai.settings.speakReminders': "Speak reminders aloud",
    'ai.settings.voice': "Voice",
    'ai.settings.testVoice': "Test voice",
    'ai.settings.noMic': "Voice input isn't available in this browser. Use the microphone on your keyboard to dictate instead.",
    'sync.title': "Sync",
    'sync.intro': "Sign in to keep your agenda in step on all your devices. Everything keeps working offline.",
    'sync.expired': "Your session has expired. Sign in again to keep syncing.",
    'sync.server': "Server",
    'sync.email': "Email",
    'sync.password': "Password",
    'sync.signIn': "Sign in",
    'sync.signingIn': "Signing in...",
    'sync.signedIn': "Signed in. Your agenda is syncing.",
    'sync.signedInAs': "Signed in as",
    'sync.signOut': "Sign out",
    'sync.signOutConfirm': "Stop syncing on this device? Your agenda stays on this device and on the server.",
    'sync.now': "Sync now",
    'sync.fillIn': "Fill in the server, your email and your password.",
    'sync.wrongLogin': "Email or password is not right.",
    'sync.serverError': "The server answered with an error ({code}). Try again later.",
    'sync.unreachable': "Can't reach the server. Check the address and your connection.",
    'sync.accountsNote': "Accounts are made by whoever runs the server.",
    'sync.howItWorks': "Changes sync automatically, also between devices that are open at the same time. If the same item changes in two places, the most recent change wins.",
    'sync.haveAccount': "I already have an account",
    'sync.status.syncing': "Syncing...",
    'sync.status.offline': "Offline, will sync when back online",
    'sync.status.error': "Couldn't sync ({code}), will retry",
    'sync.status.never': "Not synced yet",
    'sync.status.justNow': "Synced just now",
    'sync.status.ago': "Synced {n} minute ago|Synced {n} minutes ago",
    'settings.title': 'Preferences',
    'settings.general': 'General',
    'settings.language': 'Language',
    'settings.auto': 'Automatic',
    'settings.theme': 'Look',
    'settings.themeAuto': '2007 (auto)',
    'settings.themeModern': 'Modern',
    'scope.moveTitle': 'Move repeating appointment',
    'event.moved': 'Moved to {when}',
    'swipe.done': 'Done',
    'swipe.reopen': 'Reopen',
    'welcome.f6': 'Drag appointments to move them, swipe tasks to finish them',
    'settings.themeLight': '2007 Light',
    'settings.themeDark': '2007 Night',
    'settings.themeClassic': 'Classic Palm',
    'settings.weekStart': 'Week starts on',
    'settings.monday': 'Monday',
    'settings.sunday': 'Sunday',
    'settings.saturday': 'Saturday',
    'settings.timeFormat': 'Time format',
    'settings.calendar': 'Calendar',
    'settings.dayStart': 'Day starts at',
    'settings.dayEnd': 'Day ends at',
    'settings.duration': 'Default length',
    'settings.defaultAlarm': 'Default alarm',
    'settings.monthText': 'Show titles in month view',
    'settings.agendaDays': 'Agenda looks ahead',
    'settings.nDays': '{n} days',
    'settings.undatedInAgenda': 'Undated tasks in agenda',
    'settings.doneInAgenda': 'Completed tasks in agenda',
    'settings.notifications': 'Alarms',
    'settings.notifyStatus': 'System notifications',
    'settings.notifyHint': 'Alarms ring while the app is open or in the background. Install it on your home screen for the best result.',
    'settings.notifyEnable': 'Turn on',
    'settings.notifyOn': 'Notifications are on',
    'settings.notifyDenied': 'Notifications are blocked. Allow them in your browser settings.',
    'settings.notifyUnsupported': 'Not supported in this browser',
    'settings.categories': 'Categories',
    'settings.addCategory': 'Add category',
    'settings.newCategory': 'New category',
    'settings.color': 'Colour',
    'settings.categoryName': 'Category name',
    'settings.deleteCategory': 'Delete category',
    'settings.deleteCategoryMsg': 'Items in "{name}" become Unfiled.',
    'settings.categoryDeleted': 'Category deleted',
    'settings.data': 'Your data',
    'settings.localNote': 'Everything is stored on this device only. Make a backup now and then.',
    'settings.memoryOnly': 'This browser blocks storage, so changes are lost when you close the page. Make a backup before leaving.',
    'settings.backup': 'Back up (.json)',
    'settings.restore': 'Restore backup',
    'settings.restoreConfirm': 'This replaces all current data with the backup. You can undo right after.',
    'settings.restoreReplace': 'Replace my data',
    'settings.restored': 'Backup restored',
    'settings.exportIcs': 'Export calendar (.ics)',
    'settings.importIcs': 'Import calendar (.ics)',
    'settings.exportVcf': 'Export contacts (.vcf)',
    'settings.importVcf': 'Import contacts (.vcf)',
    'settings.importedIcs': 'Imported {e} appointments and {t} tasks',
    'settings.importedVcf': 'Imported {n} contact|Imported {n} contacts',
    'settings.badFile': 'That file could not be read.',
    'settings.demo': 'Add sample data',
    'settings.demoLoaded': 'Sample data added',
    'settings.erase': 'Erase everything',
    'settings.eraseConfirm': 'Delete all appointments, tasks, contacts and memos?',
    'settings.erased': 'Everything erased',
    'settings.about': 'PalmOS Agenda. A tribute to Agendus by Iambic and the Palm OS organizers.',
    'settings.stats': '{e} appointments, {t} tasks, {c} contacts, {m} memos',
  },

  nl: {
    'nav.agenda': 'Agenda',
    'nav.calendar': 'Kalender',
    'nav.tasks': 'Taken',
    'nav.memos': 'Memo’s',
    'nav.contacts': 'Contacten',
    'view.day': 'Dag',
    'view.week': 'Week',
    'view.month': 'Maand',
    'view.year': 'Jaar',
    'view.list': 'Lijst',

    'common.today': 'Vandaag',
    'common.tomorrow': 'Morgen',
    'common.yesterday': 'Gisteren',
    'common.new': 'Nieuw',
    'common.save': 'Opslaan',
    'common.cancel': 'Annuleren',
    'common.close': 'Sluiten',
    'common.delete': 'Verwijderen',
    'common.edit': 'Bewerken',
    'common.done': 'Klaar',
    'common.duplicate': 'Kopiëren',
    'common.remove': 'Weghalen',
    'common.search': 'Zoeken',
    'common.undo': 'Ongedaan maken',
    'common.on': 'AAN',
    'common.off': 'UIT',
    'common.next': 'Volgende',
    'common.previous': 'Vorige',

    'filter.all': 'Alles',
    'filter.label': 'Categorie',
    'cat.none': 'Ongeordend',
    'cat.business': 'Werk',
    'cat.personal': 'Persoonlijk',
    'cat.family': 'Familie',
    'cat.holiday': 'Vakantie',

    'week.short': 'Wk {n}',
    'week.long': 'Week {n}',
    'dur.min': '{n} min',
    'dur.h': '{n} u',
    'dur.hmin': '{h} u {m} min',
    'alarm.none': 'Geen alarm',
    'alarm.atTime': 'Bij aanvang',
    'alarm.minutes': '{n} minuut vooraf|{n} minuten vooraf',
    'alarm.hours': '{n} uur vooraf',
    'alarm.days': '{n} dag vooraf|{n} dagen vooraf',
    'alarm.minutesPlain': '{n} minuut|{n} minuten',

    'agenda.appointments': 'Afspraken',
    'agenda.contacts': 'Mensen vandaag',
    'agenda.upcoming': 'Komende {n} dagen',
    'agenda.all': 'Alles',
    'agenda.countEvents': '{n} afspraak|{n} afspraken',
    'agenda.countTasks': '{n} taak|{n} taken',
    'agenda.now': 'Nu',
    'agenda.next': 'Hierna',
    'agenda.noAppointments': 'Geen afspraken. Geniet van de vrije tijd.',
    'agenda.noTasks': 'Niets te doen.',
    'agenda.noUpcoming': 'Nog niets gepland.',
    'agenda.emptyHint': 'Je agenda is leeg. Zet je eerste afspraak erin om te beginnen.',

    'day.nothing': 'Niets gepland op deze dag.',
    'day.tasksDue': '{n} taak voor deze dag|{n} taken voor deze dag',
    'month.openDay': 'Dagweergave',
    'list.more': 'Meer tonen (tot {date})',
    'list.nothing': 'Niets gepland in de komende {n} dagen.',
    'birthday.of': 'Verjaardag {name}',

    'event.new': 'Nieuwe afspraak',
    'event.edit': 'Afspraak bewerken',
    'event.details': 'Afspraak',
    'event.untitled': '(geen titel)',
    'event.allDay': 'Hele dag',
    'event.titlePh': 'Wat gaat er gebeuren?',
    'event.saved': 'Afspraak opgeslagen',
    'event.deleted': 'Afspraak verwijderd',
    'event.newAt': 'Nieuwe afspraak om {time}',

    'editor.icon': 'Kies icoon',
    'editor.noIcon': 'Geen icoon',
    'editor.starts': 'Begint',
    'editor.ends': 'Eindigt',
    'editor.time': 'Tijd',
    'editor.repeat': 'Herhalen',
    'editor.alarm': 'Alarm',
    'editor.category': 'Categorie',
    'editor.location': 'Locatie',
    'editor.locationPh': 'Waar?',
    'editor.contacts': 'Contacten',
    'editor.addContact': 'Contact koppelen',
    'editor.notes': 'Notitie',

    'repeat.none': 'Herhaalt niet',
    'repeat.daily': 'Dagelijks',
    'repeat.weekly': 'Wekelijks',
    'repeat.monthlyDate': 'Maandelijks (zelfde datum)',
    'repeat.monthlyWeekday': 'Maandelijks (zelfde weekdag)',
    'repeat.yearly': 'Jaarlijks',
    'repeat.interval': 'Elke',
    'repeat.until': 'Tot en met',
    'repeat.every.daily': 'Elke dag',
    'repeat.every.weekly': 'Elke week',
    'repeat.every.monthly': 'Elke maand',
    'repeat.every.yearly': 'Elk jaar',
    'repeat.everyN.daily': 'Elke {n} dagen',
    'repeat.everyN.weekly': 'Elke {n} weken',
    'repeat.everyN.monthly': 'Elke {n} maanden',
    'repeat.everyN.yearly': 'Elke {n} jaar',
    'repeat.nth.1': 'eerste',
    'repeat.nth.2': 'tweede',
    'repeat.nth.3': 'derde',
    'repeat.nth.4': 'vierde',
    'repeat.nth.5': 'laatste',

    'scope.editTitle': 'Herhalende afspraak wijzigen',
    'scope.deleteTitle': 'Herhalende afspraak verwijderen',
    'scope.message': 'Voor welke keren geldt dit?',
    'scope.one': 'Alleen deze',
    'scope.future': 'Deze en volgende',
    'scope.all': 'Allemaal',

    'tasks.title': 'Taken',
    'tasks.quickAdd': 'Typ een taak en druk op Enter',
    'tasks.filter.all': 'Open',
    'tasks.filter.today': 'Nu doen',
    'tasks.filter.upcoming': 'Binnenkort',
    'tasks.filter.nodate': 'Zonder datum',
    'tasks.filter.done': 'Afgerond',
    'tasks.empty.all': 'Alles af. Niets open.',
    'tasks.empty.today': 'Niets voor vandaag.',
    'tasks.empty.upcoming': 'Geen taken gepland.',
    'tasks.empty.nodate': 'Geen taken zonder datum.',
    'tasks.empty.done': 'Nog niets afgerond.',
    'tasks.overdue': 'Te laat',
    'tasks.overdueN': '{n} te laat',
    'tasks.noDate': 'Geen datum',
    'tasks.purge': 'Afgeronde taken verwijderen',
    'tasks.purgeConfirm': 'Alle afgeronde taken verwijderen? Je kunt dit direct daarna ongedaan maken.',
    'tasks.purged': 'Afgeronde taken verwijderd',

    'task.new': 'Nieuwe taak',
    'task.edit': 'Taak bewerken',
    'task.untitled': '(geen titel)',
    'task.titlePh': 'Wat moet er gebeuren?',
    'task.priority': 'Prioriteit',
    'task.due': 'Deadline',
    'task.nextWeek': 'Volgende week',
    'task.reminder': 'Herinnering',
    'task.done': 'Afgerond',
    'task.toggle': 'Afvinken',
    'task.saved': 'Taak opgeslagen',
    'task.added': 'Taak toegevoegd',
    'task.deleted': 'Taak verwijderd',
    'task.completed': 'Taak afgerond',
    'task.rolled': 'Gedaan. Volgende keer: {date}',
    'task.completions': 'Tot nu toe {n} keer afgerond.',

    'followup.title': 'Opvolgen',
    'followup.message': 'Maak een vervolg met dezelfde contacten en categorie.',
    'followup.prefix': 'Opvolgen: {title}',
    'followup.taskTomorrow': 'Taak voor morgen',
    'followup.taskWeek': 'Taak voor volgende week',
    'followup.eventWeek': 'Afspraak volgende week',
    'followup.eventPick': 'Afspraak, zelf datum kiezen',
    'followup.created': 'Vervolg aangemaakt',

    'contacts.title': 'Contacten',
    'contacts.search': 'Zoek in {n} contacten',
    'contacts.empty': 'Nog geen contacten.',
    'contacts.noMatch': 'Geen contacten gevonden.',
    'contacts.unnamed': '(geen naam)',
    'contact.new': 'Nieuw contact',
    'contact.edit': 'Contact bewerken',
    'contact.details': 'Contact',
    'contact.call': 'Bellen',
    'contact.sms': 'Sms',
    'contact.email': 'Mailen',
    'contact.emailLabel': 'E-mail',
    'contact.map': 'Kaart',
    'contact.firstName': 'Voornaam',
    'contact.lastName': 'Achternaam',
    'contact.company': 'Bedrijf',
    'contact.jobTitle': 'Functie',
    'contact.phones': 'Telefoonnummers',
    'contact.emails': 'E-mailadressen',
    'contact.addPhone': 'Nummer toevoegen',
    'contact.addEmail': 'E-mail toevoegen',
    'contact.address': 'Adres',
    'contact.birthday': 'Verjaardag',
    'contact.noYear': 'Jaar onbekend',
    'contact.website': 'Website',
    'contact.history': 'Geschiedenis',
    'contact.upcoming': 'Gepland',
    'contact.past': 'Eerdere afspraken',
    'contact.noHistory': 'Nog niets gekoppeld aan dit contact.',
    'contact.saved': 'Contact opgeslagen',
    'contact.deleted': 'Contact verwijderd',
    'contact.meetWith': 'Afspraak met {name}',
    'contact.callName': '{name} bellen',
    'phone.mobile': 'Mobiel',
    'phone.work': 'Werk',
    'phone.home': 'Thuis',
    'phone.pager': 'Pieper',
    'phone.fax': 'Fax',
    'phone.other': 'Overig',

    'memos.title': 'Memo’s',
    'memos.search': 'Zoek in memo’s',
    'memos.empty': 'Nog geen memo’s.',
    'memos.noMatch': 'Geen memo’s gevonden.',
    'memo.new': 'Nieuwe memo',
    'memo.untitled': '(lege memo)',
    'memo.placeholder': 'Begin met typen. De eerste regel wordt de titel.',
    'memo.deleted': 'Memo verwijderd',

    'reminder.title': 'Herinnering',
    'reminder.followUp': 'Opvolgen',
    'reminder.snooze': 'Sluimeren',
    'reminder.none': 'Geen',
    'reminder.ok': 'OK',
    'reminder.open': 'Openen',
    'reminder.complete': 'Afvinken',
    'reminder.snoozed': 'Sluimert {n} minuten',

    'goto.title': 'Naar datum',
    'goto.date': 'Datum',

    'search.placeholder': 'Afspraken, taken, contacten, memo’s',
    'search.hint': 'Typ om overal tegelijk te zoeken.',
    'search.none': 'Niets gevonden voor "{q}".',
    'search.appointments': 'Afspraken',

    'welcome.title': 'Welkom bij PalmOS Agenda',
    'welcome.text': 'De klassieke Palm-organizer, opnieuw gebouwd voor je telefoon. Alles wat je plant blijft op dit apparaat.',
    'welcome.f1': 'Agenda: afspraken, taken en mensen van vandaag op één scherm',
    'welcome.f2': 'Dag, week, maand, jaar en lijst',
    'welcome.f3': 'Koppel contacten aan afspraken en taken',
    'welcome.f4': 'Alarmen met sluimeren en opvolgen',
    'welcome.f5': 'Privé: geen account, werkt offline',
    'welcome.demo': 'Begin met voorbeelddata',
    'welcome.empty': 'Begin leeg',

    'ai.talkTo': "Praat met {name}",
    'ai.talk': "Praat",
    'ai.speak': "Spreek",
    'ai.send': "Verstuur",
    'ai.placeholder': "Vraag of zeg me iets",
    'ai.placeholderMic': "Typ, of tik op Praat en spreek",
    'ai.standby': "{name} staat paraat. Tik om te praten.",
    'ai.greet': "{name} online. Waarmee kan ik helpen?",
    'ai.greetNews': "Online. {n} ding vraagt je aandacht.|Online. {n} dingen vragen je aandacht.",
    'ai.dismiss': "Wegdoen",
    'ai.open': "Open",
    'ai.route': "Route",
    'ai.textLate': "Sms {name}",
    'ai.lateMessage': "Hoi! Ik ben onderweg, tot zo. ({title})",
    'ai.moveToday': "Naar vandaag",
    'ai.moveTomorrow': "Naar morgen",
    'ai.moved': "Taken verplaatst",
    'ai.giftTask': "Herinner me: cadeau",
    'ai.giftTitle': "Cadeau regelen voor {name}",
    'ai.at': " bij {place}",
    'ai.insight.next': "{title} over {n} minuut{where}, om {time}.|{title} over {n} minuten{where}, om {time}.",
    'ai.insight.clash': "{a} en {b} overlappen {day} om {time}.",
    'ai.insight.busy': "Geen adempauze van {from} tot {to}. Zal ik een pauze voor je zoeken?",
    'ai.insight.overdue': "\"{title}\" is te laat.|{n} taken zijn te laat, te beginnen met \"{title}\".",
    'ai.insight.bdayToday': "{name} is vandaag jarig{age}.",
    'ai.insight.bdayTomorrow': "{name} is morgen jarig{age}.",
    'ai.insight.early': "Morgen vroeg op: {title} om {time}.",
    'ai.brief.morning': "Goedemorgen{name}.",
    'ai.brief.afternoon': "Goedemiddag{name}.",
    'ai.brief.evening': "Goedenavond{name}.",
    'ai.brief.free': "Er staat vandaag niets meer in de agenda.",
    'ai.brief.count': "Je hebt vandaag nog {n} afspraak:|Je hebt vandaag nog {n} afspraken:",
    'ai.brief.atTime': "om {time}",
    'ai.brief.tasks': "En {n} taak op je lijst.|En {n} taken op je lijst.",
    'ai.chip.next': "Wat is het volgende?",
    'ai.chip.nextPrompt': "Wat is het volgende in mijn agenda?",
    'ai.chip.brief': "Briefing",
    'ai.chip.briefPrompt': "Geef me een korte briefing van mijn dag.",
    'ai.chip.tomorrow': "Plan morgen",
    'ai.chip.tomorrowPrompt': "Hoe ziet morgen eruit, en moet ik iets voorbereiden?",
    'ai.chip.task': "Taak toevoegen",
    'ai.chip.taskPrefix': "Herinner me om ",
    'ai.status.listening': "Ik luister...",
    'ai.status.thinking': "Even denken...",
    'ai.status.working': "Bezig met je agenda...",
    'ai.status.speaking': "Spreekt",
    'ai.status.ready': "Klaar",
    'ai.status.offline': "Offline modus",
    'ai.done': "Gedaan.",
    'ai.undone': "Ongedaan gemaakt",
    'ai.refused': "Daar kan ik je helaas niet mee helpen.",
    'ai.sendText': "Sms naar {name}",
    'ai.sendEmail': "Mail {name}",
    'ai.connect': "Claude koppelen",
    'ai.localNote': "Offline modus: ik begrijp eenvoudige opdrachten. Koppel Claude in Voorkeuren om vrij te praten.",
    'ai.local.next': "Hierna: {title}, {when}.",
    'ai.local.nothingNext': "Niets gepland voor de komende twee weken.",
    'ai.local.dayFree': "Die dag is nog vrij.",
    'ai.local.dayCount': "{n} afspraak:|{n} afspraken:",
    'ai.local.taskAdded': "Op je lijst gezet: {title}.",
    'ai.local.needKey': "Offline ken ik maar een paar opdrachten, zoals \"wat is het volgende\", \"vandaag\", \"morgen\" of \"herinner me om...\". Koppel Claude in Voorkeuren en ik begrijp alles.",
    'ai.error.auth': "Claude weigerde de verbinding. Controleer de API-sleutel in Voorkeuren.",
    'ai.error.rate': "Claude heeft het even druk. Probeer het zo nog eens.",
    'ai.error.network': "Ik kan Claude niet bereiken. Ben je online?",
    'ai.error.bad': "Claude accepteerde dat verzoek niet. Probeer het anders te zeggen.",
    'ai.error.api': "Er ging iets mis bij Claude. Probeer het zo nog eens.",
    'ai.error.other': "Er ging iets mis. Probeer het nog eens.",
    'ai.error.mic': "Ik mag de microfoon niet gebruiken. Sta het toe in je browserinstellingen, of typ.",
    'ai.reminderSay': "{name}een herinnering:",
    'ai.voiceTest': "Dit is {name}. Alle systemen werken perfect.",
    'ai.keyInvalid': "Dat lijkt geen Claude API-sleutel (die begint met sk-ant-).",
    'ai.keySaved': "Claude gekoppeld",
    'ai.keyRemoved': "API-sleutel verwijderd",
    'ai.settings.title': "Assistent",
    'ai.settings.name': "Naam van de assistent",
    'ai.settings.userName': "Jouw naam",
    'ai.settings.userNamePh': "Optioneel",
    'ai.settings.key': "Claude API-sleutel",
    'ai.settings.keyHint': "Nodig om vrij te praten. Zonder werken eenvoudige opdrachten nog steeds.",
    'ai.settings.connected': "Gekoppeld",
    'ai.settings.forget': "Verwijder",
    'ai.settings.keyPrivacy': "Staat alleen op dit apparaat en gaat alleen naar Anthropic. Hij zit niet in back-ups. Maak een sleutel en stel een maandlimiet in op",
    'ai.settings.model': "Model",
    'ai.settings.modelHint': "Opus is het slimst; Haiku is het snelst en goedkoopst.",
    'ai.settings.proactive': "Uit zichzelf meedenken",
    'ai.settings.proactiveHint': "Tips over overlap, te late taken, verjaardagen en wat er komt.",
    'ai.settings.speak': "Antwoorden hardop uitspreken",
    'ai.settings.speakReminders': "Herinneringen hardop uitspreken",
    'ai.settings.voice': "Stem",
    'ai.settings.testVoice': "Stem testen",
    'ai.settings.noMic': "Spraakinvoer is niet beschikbaar in deze browser. Gebruik de microfoon op je toetsenbord om te dicteren.",
    'sync.title': "Synchroniseren",
    'sync.intro': "Log in om je agenda op al je apparaten gelijk te houden. Alles blijft offline werken.",
    'sync.expired': "Je sessie is verlopen. Log opnieuw in om te blijven synchroniseren.",
    'sync.server': "Server",
    'sync.email': "E-mail",
    'sync.password': "Wachtwoord",
    'sync.signIn': "Inloggen",
    'sync.signingIn': "Bezig met inloggen...",
    'sync.signedIn': "Ingelogd. Je agenda wordt gesynchroniseerd.",
    'sync.signedInAs': "Ingelogd als",
    'sync.signOut': "Uitloggen",
    'sync.signOutConfirm': "Stoppen met synchroniseren op dit apparaat? Je agenda blijft op dit apparaat en op de server staan.",
    'sync.now': "Nu synchroniseren",
    'sync.fillIn': "Vul de server, je e-mail en je wachtwoord in.",
    'sync.wrongLogin': "E-mail of wachtwoord klopt niet.",
    'sync.serverError': "De server gaf een fout ({code}). Probeer het later nog eens.",
    'sync.unreachable': "De server is niet bereikbaar. Controleer het adres en je verbinding.",
    'sync.accountsNote': "Accounts worden gemaakt door wie de server beheert.",
    'sync.howItWorks': "Wijzigingen gaan automatisch over, ook tussen apparaten die tegelijk open staan. Wordt hetzelfde item op twee plekken gewijzigd, dan wint de laatste wijziging.",
    'sync.haveAccount': "Ik heb al een account",
    'sync.status.syncing': "Bezig...",
    'sync.status.offline': "Offline, synchroniseert zodra je weer online bent",
    'sync.status.error': "Synchroniseren lukte niet ({code}), probeert het opnieuw",
    'sync.status.never': "Nog niet gesynchroniseerd",
    'sync.status.justNow': "Zojuist gesynchroniseerd",
    'sync.status.ago': "{n} minuut geleden gesynchroniseerd|{n} minuten geleden gesynchroniseerd",
    'settings.title': 'Voorkeuren',
    'settings.general': 'Algemeen',
    'settings.language': 'Taal',
    'settings.auto': 'Automatisch',
    'settings.theme': 'Uiterlijk',
    'settings.themeAuto': '2007 (auto)',
    'settings.themeModern': 'Modern',
    'scope.moveTitle': 'Herhalende afspraak verplaatsen',
    'event.moved': 'Verplaatst naar {when}',
    'swipe.done': 'Klaar',
    'swipe.reopen': 'Heropenen',
    'welcome.f6': 'Sleep afspraken om ze te verplaatsen, veeg taken weg als ze af zijn',
    'settings.themeLight': '2007 Licht',
    'settings.themeDark': '2007 Nacht',
    'settings.themeClassic': 'Klassieke Palm',
    'settings.weekStart': 'Week begint op',
    'settings.monday': 'Maandag',
    'settings.sunday': 'Zondag',
    'settings.saturday': 'Zaterdag',
    'settings.timeFormat': 'Tijdnotatie',
    'settings.calendar': 'Kalender',
    'settings.dayStart': 'Dag begint om',
    'settings.dayEnd': 'Dag eindigt om',
    'settings.duration': 'Standaardduur',
    'settings.defaultAlarm': 'Standaardalarm',
    'settings.monthText': 'Titels tonen in maandweergave',
    'settings.agendaDays': 'Agenda kijkt vooruit',
    'settings.nDays': '{n} dagen',
    'settings.undatedInAgenda': 'Taken zonder datum in agenda',
    'settings.doneInAgenda': 'Afgeronde taken in agenda',
    'settings.notifications': 'Alarmen',
    'settings.notifyStatus': 'Systeemmeldingen',
    'settings.notifyHint': 'Alarmen gaan af zolang de app open is of op de achtergrond draait. Zet de app op je beginscherm voor het beste resultaat.',
    'settings.notifyEnable': 'Aanzetten',
    'settings.notifyOn': 'Meldingen staan aan',
    'settings.notifyDenied': 'Meldingen zijn geblokkeerd. Sta ze toe in je browserinstellingen.',
    'settings.notifyUnsupported': 'Niet beschikbaar in deze browser',
    'settings.categories': 'Categorieën',
    'settings.addCategory': 'Categorie toevoegen',
    'settings.newCategory': 'Nieuwe categorie',
    'settings.color': 'Kleur',
    'settings.categoryName': 'Naam categorie',
    'settings.deleteCategory': 'Categorie verwijderen',
    'settings.deleteCategoryMsg': 'Items in "{name}" worden Ongeordend.',
    'settings.categoryDeleted': 'Categorie verwijderd',
    'settings.data': 'Je gegevens',
    'settings.localNote': 'Alles staat alleen op dit apparaat. Maak af en toe een back-up.',
    'settings.memoryOnly': 'Deze browser blokkeert opslag, dus wijzigingen zijn weg als je de pagina sluit. Maak een back-up voordat je weggaat.',
    'settings.backup': 'Back-up maken (.json)',
    'settings.restore': 'Back-up terugzetten',
    'settings.restoreConfirm': 'Dit vervangt al je huidige gegevens door de back-up. Je kunt dit direct daarna ongedaan maken.',
    'settings.restoreReplace': 'Vervang mijn gegevens',
    'settings.restored': 'Back-up teruggezet',
    'settings.exportIcs': 'Kalender exporteren (.ics)',
    'settings.importIcs': 'Kalender importeren (.ics)',
    'settings.exportVcf': 'Contacten exporteren (.vcf)',
    'settings.importVcf': 'Contacten importeren (.vcf)',
    'settings.importedIcs': '{e} afspraken en {t} taken geïmporteerd',
    'settings.importedVcf': '{n} contacten geïmporteerd',
    'settings.badFile': 'Dit bestand kon niet worden gelezen.',
    'settings.demo': 'Voorbeelddata toevoegen',
    'settings.demoLoaded': 'Voorbeelddata toegevoegd',
    'settings.erase': 'Alles wissen',
    'settings.eraseConfirm': 'Alle afspraken, taken, contacten en memo’s verwijderen?',
    'settings.erased': 'Alles gewist',
    'settings.about': 'PalmOS Agenda. Een eerbetoon aan Agendus van Iambic en de organizers van Palm OS.',
    'settings.stats': '{e} afspraken, {t} taken, {c} contacten, {m} memo’s',

    'demo.dentist': 'Tandarts',
    'demo.standup': 'Teamoverleg',
    'demo.gym': 'Sportschool',
    'demo.lunch': 'Lunch met Cathy',
    'demo.conference': 'Marketingcongres',
    'demo.payday': 'Salaris',
    'demo.flight': 'Vlucht naar Lissabon',
    'demo.review': 'Projectreview',
    'demo.boarding': 'Instapkaart printen',
    'demo.dinner': 'Tafel reserveren voor het diner',
    'demo.callWilliam': 'William bellen over de offerte',
    'demo.birthdayReminder': 'Verjaardagsherinnering sturen',
    'demo.plants': 'Planten water geven',
    'demo.passport': 'Paspoort verlengen',
    'demo.memo1': 'Paklijst Lissabon\n- Paspoort\n- Oplader\n- Zonnebril\n- Reisgids',
    'demo.memo2': 'Ideeën voor de congrestalk\nBegin met het Palm-verhaal en laat dan de nieuwe roadmap zien.',
  },
};
